PR for review
visva-dev/Library pull request #1
Opened 2020-10-29 14:06 UTC by visva-dev

## Project Library
- User is able to create books with a title, author, pages parameters.
- Created book is added to the books table and shown in the browser under creation form.
- The user is able to delete the book from the books table.

2020-10-29 14:47 UTC, rOluochKe requested changes
Hello @visva-dev and @Guy-Gustave 
### You have done well so far :clap: However, you have a few issues to fix:-
- [x] Add linting file with all the required dependencies then add configuration - [follow this guide](https://github.com/microverseinc/linters-config/tree/master/javascript)
- [x] Each Book displayed has a button to toggle the Book read status
- [ ] Separate dom manipulation from application logic. Foolw the examples below
### Make the changes and submit for another code review. Good luck.
- Happy coding!

2020-10-29 14:48 UTC, rOluochKe commented on script.js
> +});
### Separte dom from app logic

2020-10-30 10:11 UTC, visva-dev commented
- Fix all issues suggested by Tse.

2020-10-30 10:39 UTC, lucasmazo23 requested changes
## Changes required 🔧
### You are doing a great job so far, and the project is looking good.

### For the project to get approved kindly implement these changes:

### Required changes:
- [ ] [REQUIRED] The project still doesn't display the toggle button, you need a button on each book so that after I added it to my library I can change the `read` status

button should be here:
![image](https://user-images.githubusercontent.com/73254040/97695517-c8578800-1a69-11eb-9dd3-a131d94cc051.png)


![image](https://user-images.githubusercontent.com/73254040/97695018-043e1d80-1a69-11eb-92d5-54d451da574b.png)
[source](https://www.theodinproject.com/courses/javascript/lessons/library)

### Optional Changes:
- [ ] [OPTIONAL] In the future, please add the package.json and package-lock.json, so that we ensure we have the same packages installed
![image](https://user-images.githubusercontent.com/73254040/97695193-48c9b900-1a69-11eb-98a4-89beb910dea2.png)
- [ ] [OPTIONAL] I think you made a better job separating the logic from the DOM manipulation, but I also think there's more room for improvement, separating files and making modules, but since this project doesn't use a packager still, I think this is kind of enough :D
### Happy coding! 💻
## Lucas Mazo

2020-11-03 13:04 UTC, rOluochKe approved these changes
Hello Team
### You got it right, well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-11-03 13:33 UTC, merged